### PR TITLE
convert all projects except ui to Netstandard 2.0

### PR DESCRIPTION
**Pull request by tommes**
As the project is about architecture, I might suggest to convert all projects except UI and Tests to netstandard 2.0 to make them reusable on all compatible platforms.

### CODE REVIEW

**Comment by Hoopie** [comment]
tommes, I could be mistaken but i believe that Persistence will not be able to update to netstandard. this is because of the dependency on EntityFrameworkCore.

```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.1" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.1" />
```
A core dll can reference a netstandard but not the reverse. You will see this error in the package manager console when attempting to create or apply a migration.

As for updating the others Domain, Common, Integration etc to netStd, +1. In fact i did this in my spin off project.

Simmo

**Comment by tommes** [comment]
Hoopie, EF Core IS netstandard, works on classic .NET 4.6.1 and higher, see also https://docs.microsoft.com/en-us/ef/core/platforms/
I didn't get any errors when restoring and compiling. 
I do a lot of work with EF Core targeting .NET full framework and that works.

**Comment by Hoopie** [comment]
Sweet. I think i got confused with a package manager issue I got in that you need to target an assembly that is either core or .net in order to get the code first migrations running.

I'm going to change my persistence proj over.. Thanks for the fact check tommes!

**Comment by JasonGT** [comment]
Good call, thanks for the contribution. 👍

**Pull request merged**
