### PR TITLE
Better exception filter

### PR DESCRIPTION
**Pull request by Sp-NNT**
This implementation of Exception allows to give client more complex and very different exception messages, and, also, you set the error status code directly in the Exception class.

### CODE REVIEW

**Comment by JasonGT** [comment]
Hi @Sp-NNT - firstly, thanks for your contribution.

I think this would be a good approach if we only dealt with HTTP clients. What if we're not dealing with a HTTP client? In that case HTTP status code would not be relevant to the client. I think the exceptions returned from Core layers should focus just on describing the problem. It will be up to the client to handle the exceptions and set status codes.

I do think the exception handling can be improved.

From an ASP.NET Core perspective, I'd like to implement the following - https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-web-apis/#problem-details.

From a CQRS / Application layer perspective, I'm considering whether or not to add and generic result class rather than using exceptions. It might look like this:

```
public class AppResult<T>
{
  public bool Succeeded { get; protected set; }
  public IEnumerable<AppError> Errors { get; set; }
  public T Data { get; protected set; }
}
```

This is similar to how ASP.NET Core Identity works; https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.identityresult?view=aspnetcore-2.2. 

What do you think?

**Comment by Sp-NNT** [comment]
@JasonGT, thanks a lot for good explanations, I got it!

Firstly, I wanted to make every query results as in Telegram Bot Api:

{
  "ok": <boolean>,
  "error_code": <integer>,
  "description": <string>,
   "result": <array> or <object>
}

but I was too lazy to do so 😳

**Comment by JasonGT** [comment]
That looks like a great approach too. Thanks for your insights, I'll keep it in mind. 👍

**Comment by rafalschmidt97** [comment]
@Sp-NNT 

Maybe it's not the perfect solution but for my needs it's good enough. I've created most popular exceptions with base class. Then I use them to get status etc.

screenshot 2019-02-16 at 19 01 46

For example:

```c#
public class BadGatewayException : CustomException
  {
    public BadGatewayException(string message)
      : base(HttpStatusCode.BadGateway, message)
    {
    }

    public BadGatewayException()
      : base(HttpStatusCode.BadGateway)
    {
    }
  }
```

```c#
public class CustomException : Exception
  {
    public CustomException(HttpStatusCode status, string message)
      : base(message)
    {
      Status = status;
    }

    public CustomException(HttpStatusCode status)
      : base(nameof(status))
    {
      Status = status;
    }

    public CustomException(string message)
      : base(message)
    {
      Status = HttpStatusCode.InternalServerError;
    }

    public CustomException()
      : base(nameof(HttpStatusCode.InternalServerError))
    {
      Status = HttpStatusCode.InternalServerError;
    }

    public HttpStatusCode Status { get; }
  }
```

and the handler:

```c#
public override void OnException(ExceptionContext context)
    {
      var status = HttpStatusCode.InternalServerError;
      object message = nameof(HttpStatusCode.InternalServerError);

      if (context.Exception is ValidationException validationException)
      {
        status = HttpStatusCode.BadRequest;
        message = RequestValidationHelper.GetValidationFailures(validationException.Errors);
      }
      else if (context.Exception is CustomException customException)
      {
        status = customException.Status;
        message = customException.Message;
      }
      else
      {
        _logger.LogCritical(context.Exception, "Unexpected Web Layer Exception:");
      }

      context.HttpContext.Response.ContentType = "application/json";
      context.HttpContext.Response.StatusCode = (int)status;
      context.Result = new JsonResult(new { status, message });
    }
```

Hope this might help some people.

**Comment by Sp-NNT** [comment]
@JasonGT Thanks a lot!

**Pull request closed without merging**
